### ISSUE TITLE
Model Size reduction in pruning?

### ISSUE THREAD

**Issue by SourabhRanade** [leimao/PyTorch-Pruning-Example#3]
Hello, Lei. I was going through one of your blogs(https://leimao.github.io/blog/PyTorch-Pruning/)  and wanted a small clarification. So in the blog, there is a mention that L1 pruning does a 50x compression in resnet . If I understand it right then the way pruning has been implemented in PyTorch does not reduce the model size. Could you please let me know how is that reduction taking place exactly? I am assuming the reduction is in the model size here

**Comment by leimao** [comment]
Please read the [last portion](https://leimao.github.io/blog/PyTorch-Pruning/#Final-Remarks) of the article. You will need to understand the difference a dense network and a sparse network. Currently the model is a sparse network stored in a dense form.
