### ISSUE TITLE
Alternative Pruning methods to reduce the size of model, beside Pytorch 

### ISSUE THREAD

**Issue by kent252** [leimao/PyTorch-Pruning-Example#5]
Dear Lei Mao, 
Thank you for your comprehensive blog about Pruning in Pytorch. However, in the conclusion, you mention that Pytorch does not support sparse tensors. 
I am a newbie in this field and my question is that any alternative ways to prune the model that can compress the size and speed up the inference time? 
Thank you once again.

**Comment by leimao** [comment]
PyTorch might have supported the [sparse tensor](https://pytorch.org/docs/stable/sparse.html) data structure in the new version. However, it's not quite useful if the compression rate is low or there is not hardware acceleration.
Typically we do structured pruning, such as pruning channels for Conv, and structured sparsity, such as 2:4 sparsity, which utilize hardware for acceleration.
You might check the following papers to begin:
* [Structural Pruning via Latency-Saliency Knapsack](https://arxiv.org/abs/2210.06659)
* [Accelerating Sparse Deep Neural Networks](https://arxiv.org/abs/2104.08378)

**Comment by kent252** [comment]
> * Structural Pruning via Latency-Saliency Knapsack

Thank you for your immediate reply. I will look for it
